server:
  port: ${APP_PORT:9191}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sultandb
    username: user
    password: user
    driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: ${DB_SQL_SHOW:on}
    hibernate:
      ddl-auto: update
    generate-ddl: on
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        enable_lazy_load_no_trans: true
logging:
  level:
    root: INFO
    org.springframework.core.env: DEBUG
